### ISSUE TITLE
PNG output with a transparent background?

### ISSUE THREAD

**Issue by RuixiZhang42** [unageek/graphest#603]
Congratulations on the 1.0.0 release!

I was wondering if the PNG output can have a transparent background. This can be very useful when showing the graphs against a color background (such as in a poster).

I have a feeling that this won’t be easy due to supersample anti-aliasing. Currently, it’s mixing the function’s color with white. But how would one go about mixing the function’s color with transparency? I have no idea…

**Comment by unageek** [comment]
Thank you for your suggestion! In fact, this is easy. I'll add this feature in the next release.
