### ISSUE TITLE
Is internet connection necessary?

### ISSUE THREAD

**Issue by ckf42** [unageek/graphest#757]
Hi. I am on a Windows machine, so I am not sure if this also happens to the MacOS build.
It appears that internet connection is required for the software to boot up.

Steps to reproduce:

1. Install while having a firewall that blocks all connections by default (installing offline should also have the same effect)
2. Start graphest

graphest will spawn ~3 processes but no gui window is shown. The problem *cannot* be reproduced if internet connection is allowed once. Afterward everything just seems to work, even after an offline reinstall.

It also appears that graphest will keep sending network requests despite there is no apparent need to do so.

Are there any features that require internet connections?

**Comment by unageek** [comment]
Hi! Thank you so much for the detailed report. I can confirm the issue.

Internet connection is required by the following codes:

https://github.com/unageek/graphest/blob/8dd6155116e4998c333960305253dfab4d1ee0ea/src/main/main.ts#L214-L216

https://github.com/unageek/graphest/blob/8dd6155116e4998c333960305253dfab4d1ee0ea/src/main/main.ts#L275

Both of them raise an exception when there is no internet connection. I will fix the issue in the next release.

**Comment by unageek** [comment]
Fixed in 3b396095d5a627cfc5f0d1e1f4f9124fe9b55c00.
