### ISSUE TITLE
My graphest isn't graphing at all

### ISSUE THREAD

**Issue by GestaltTrickster** [unageek/graphest#817]
Hello! I installed graphest and the graphs aren't showing up at all! I tried any function and they still don't show up. I don't know what the problem is. I'm on windows 11, and when i tried to install it it blocked it from installing. Am I missing a file? I also read the readme file and nothing about my problem was addressed

**Comment by unageek** [comment]
>when i tried to install it it blocked it from installing

Could you elaborate on this point?

**Comment by GestaltTrickster** [comment]
> Could you elaborate on this point?
It said Microsoft defender Smartscreeen protected my pc by blocking it  and to not run the app

**Comment by unageek** [comment]
I've released a few new versions. Please try them and let me know if that work.
