### ISSUE TITLE
sin(x^2+y^2)=0.5 spatial-aliasing

### ISSUE THREAD

**Issue by Firestar-Reimu** [unageek/graphest#989]
in low resolution it is correct

![image](https://github.com/unageek/graphest/assets/65082432/e893f7dc-06e6-476b-9549-d469a6cedb16)

in high resolution

![image](https://github.com/unageek/graphest/assets/65082432/40acf9a4-92ef-49db-aca5-180dcafe7bd8)

this is a famous problem because of spatial-aliasing

https://www.zhihu.com/question/624348562

**Comment by unageek** [comment]
Here is a rendering of the graph with the maximum antialiasing setting (25x25), which almost eliminates the aliasing effect:

![graph](https://github.com/unageek/graphest/assets/29035331/2ab02599-9413-4f25-a653-6bc7282ed760)

<img width="1032" alt="image" src="https://github.com/unageek/graphest/assets/29035331/68dc7219-eeaa-4c4a-b0e9-1ec28edc7287">

**Comment by farteryhr** [comment]
it might be considered to allow also subdivision (and gamma correct?) in live mode as, in fact, the 1px-limited outcome in the zigzag part will be rendered like visually line width of sqrt2 px, thus a bit darker than the axis-aligned part.
